{
  "active_lock_reason": null,
  "assignee": null,
  "assignees": [],
  "author_association": "MEMBER",
  "body": "When a raw block PV is used as a filesystem one in a pod (i.e. in pod.spec.containers[x].volumeMounts), kubelet correctly won't start the pod, but it does not give user any information why.\r\n\r\nIn pod events I can't see anything useful:\r\n\r\n```\r\nEvents:\r\n  Type     Reason                  Age                    From                                                 Message\r\n  ----     ------                  ----                   ----                                                 -------\r\n  Normal   Scheduled               9m13s                  default-scheduler                                    Successfully assigned volumemode-206/security-context-d213f352-cd45-48ca-bb28-268a24ec75f8 to ip-10-0-160-149.us-east-2.compute.internal\r\n  Warning  FailedAttachVolume      9m11s (x3 over 9m12s)  attachdetach-controller                              AttachVolume.Attach failed for volume \"pvc-6efadcf1-9e57-11e9-bf6d-0a9ea8760cec\" : \"Error attaching EBS volume \\\"vol-007031b5e356a6786\\\"\" to instance \"i-0daef3d471605cebf\" since volume is in \"creating\" state\r\n  Normal   SuccessfulAttachVolume  9m5s                   attachdetach-controller                              AttachVolume.Attach succeeded for volume \"pvc-6efadcf1-9e57-11e9-bf6d-0a9ea8760cec\"\r\n  Warning  FailedMount             24s (x4 over 7m10s)    kubelet, ip-10-0-160-149.us-east-2.compute.internal  Unable to mount volumes for pod \"security-context-d213f352-cd45-48ca-bb28-268a24ec75f8_volumemode-206(70902de5-9e57-11e9-bf6d-0a9ea8760cec)\": timeout expired waiting for volumes to attach or mount for pod \"volumemode-206\"/\"security-context-d213f352-cd45-48ca-bb28-268a24ec75f8\". list of unmounted volumes=[volume1]. list of unattached volumes=[volume1 default-token-h4xcm]\r\n```\r\n\r\nThe pod is `ContainerCreating` forever. It should get `Failed` with a clear message.\r\n\r\n\r\nIn kubelet logs I can see:\r\n```\r\ndesired_state_of_world_populator.go:296] Error processing volume \"volume1\" for pod \"security-context-d213f352-cd45-48ca-bb28-268a24ec75f8_volumemode-206(70902de5-9e57-11e9-bf6d-0a9ea8760cec)\": Volume \"volume1\" has volumeMode \"Block\", but is specified in volumeMounts for pod \"volumemode-206\"/\"security-context-d213f352-cd45-48ca-bb28-268a24ec75f8\"\r\n```\r\n\r\n/sig storage\r\n/kind bug\r\n/priority important-soon",
  "closed_at": "2019-08-05T22:08:17Z",
  "closed_by": {
    "avatar_url": "https://avatars0.githubusercontent.com/u/20407524?v=4",
    "events_url": "https://api.github.com/users/k8s-ci-robot/events{/privacy}",
    "followers_url": "https://api.github.com/users/k8s-ci-robot/followers",
    "following_url": "https://api.github.com/users/k8s-ci-robot/following{/other_user}",
    "gists_url": "https://api.github.com/users/k8s-ci-robot/gists{/gist_id}",
    "gravatar_id": "",
    "html_url": "https://github.com/k8s-ci-robot",
    "id": 20407524,
    "login": "k8s-ci-robot",
    "node_id": "MDQ6VXNlcjIwNDA3NTI0",
    "organizations_url": "https://api.github.com/users/k8s-ci-robot/orgs",
    "received_events_url": "https://api.github.com/users/k8s-ci-robot/received_events",
    "repos_url": "https://api.github.com/users/k8s-ci-robot/repos",
    "site_admin": false,
    "starred_url": "https://api.github.com/users/k8s-ci-robot/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/k8s-ci-robot/subscriptions",
    "type": "User",
    "url": "https://api.github.com/users/k8s-ci-robot"
  },
  "comments": 6,
  "comments_url": "https://api.github.com/repos/kubernetes/kubernetes/issues/79794/comments",
  "created_at": "2019-07-04T12:41:44Z",
  "events_url": "https://api.github.com/repos/kubernetes/kubernetes/issues/79794/events",
  "html_url": "https://github.com/kubernetes/kubernetes/issues/79794",
  "id": 464245834,
  "labels": [
    {
      "color": "e11d21",
      "default": false,
      "description": "Categorizes issue or PR as related to a bug.",
      "id": 105146071,
      "name": "kind/bug",
      "node_id": "MDU6TGFiZWwxMDUxNDYwNzE=",
      "url": "https://api.github.com/repos/kubernetes/kubernetes/labels/kind/bug"
    },
    {
      "color": "eb6420",
      "default": false,
      "description": "Must be staffed and worked on either currently, or very soon, ideally in time for the next release.",
      "id": 114528223,
      "name": "priority/important-soon",
      "node_id": "MDU6TGFiZWwxMTQ1MjgyMjM=",
      "url": "https://api.github.com/repos/kubernetes/kubernetes/labels/priority/important-soon"
    },
    {
      "color": "d2b48c",
      "default": false,
      "description": "Categorizes an issue or PR as relevant to SIG Node.",
      "id": 173493665,
      "name": "sig/node",
      "node_id": "MDU6TGFiZWwxNzM0OTM2NjU=",
      "url": "https://api.github.com/repos/kubernetes/kubernetes/labels/sig/node"
    },
    {
      "color": "d2b48c",
      "default": false,
      "description": "Categorizes an issue or PR as relevant to SIG Storage.",
      "id": 169428334,
      "name": "sig/storage",
      "node_id": "MDU6TGFiZWwxNjk0MjgzMzQ=",
      "url": "https://api.github.com/repos/kubernetes/kubernetes/labels/sig/storage"
    }
  ],
  "labels_url": "https://api.github.com/repos/kubernetes/kubernetes/issues/79794/labels{/name}",
  "locked": false,
  "milestone": null,
  "node_id": "MDU6SXNzdWU0NjQyNDU4MzQ=",
  "number": 79794,
  "performed_via_github_app": null,
  "repository_url": "https://api.github.com/repos/kubernetes/kubernetes",
  "state": "closed",
  "title": "Block volume used as filesystem in a pod does not give clear error message",
  "updated_at": "2019-08-05T22:08:17Z",
  "url": "https://api.github.com/repos/kubernetes/kubernetes/issues/79794",
  "user": {
    "avatar_url": "https://avatars2.githubusercontent.com/u/1745006?v=4",
    "events_url": "https://api.github.com/users/jsafrane/events{/privacy}",
    "followers_url": "https://api.github.com/users/jsafrane/followers",
    "following_url": "https://api.github.com/users/jsafrane/following{/other_user}",
    "gists_url": "https://api.github.com/users/jsafrane/gists{/gist_id}",
    "gravatar_id": "",
    "html_url": "https://github.com/jsafrane",
    "id": 1745006,
    "login": "jsafrane",
    "node_id": "MDQ6VXNlcjE3NDUwMDY=",
    "organizations_url": "https://api.github.com/users/jsafrane/orgs",
    "received_events_url": "https://api.github.com/users/jsafrane/received_events",
    "repos_url": "https://api.github.com/users/jsafrane/repos",
    "site_admin": false,
    "starred_url": "https://api.github.com/users/jsafrane/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/jsafrane/subscriptions",
    "type": "User",
    "url": "https://api.github.com/users/jsafrane"
  }
}