{
  "active_lock_reason": null,
  "assignee": {
    "avatar_url": "https://avatars3.githubusercontent.com/u/10743879?v=4",
    "events_url": "https://api.github.com/users/wojtek-t/events{/privacy}",
    "followers_url": "https://api.github.com/users/wojtek-t/followers",
    "following_url": "https://api.github.com/users/wojtek-t/following{/other_user}",
    "gists_url": "https://api.github.com/users/wojtek-t/gists{/gist_id}",
    "gravatar_id": "",
    "html_url": "https://github.com/wojtek-t",
    "id": 10743879,
    "login": "wojtek-t",
    "node_id": "MDQ6VXNlcjEwNzQzODc5",
    "organizations_url": "https://api.github.com/users/wojtek-t/orgs",
    "received_events_url": "https://api.github.com/users/wojtek-t/received_events",
    "repos_url": "https://api.github.com/users/wojtek-t/repos",
    "site_admin": false,
    "starred_url": "https://api.github.com/users/wojtek-t/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/wojtek-t/subscriptions",
    "type": "User",
    "url": "https://api.github.com/users/wojtek-t"
  },
  "assignees": [
    {
      "avatar_url": "https://avatars3.githubusercontent.com/u/10743879?v=4",
      "events_url": "https://api.github.com/users/wojtek-t/events{/privacy}",
      "followers_url": "https://api.github.com/users/wojtek-t/followers",
      "following_url": "https://api.github.com/users/wojtek-t/following{/other_user}",
      "gists_url": "https://api.github.com/users/wojtek-t/gists{/gist_id}",
      "gravatar_id": "",
      "html_url": "https://github.com/wojtek-t",
      "id": 10743879,
      "login": "wojtek-t",
      "node_id": "MDQ6VXNlcjEwNzQzODc5",
      "organizations_url": "https://api.github.com/users/wojtek-t/orgs",
      "received_events_url": "https://api.github.com/users/wojtek-t/received_events",
      "repos_url": "https://api.github.com/users/wojtek-t/repos",
      "site_admin": false,
      "starred_url": "https://api.github.com/users/wojtek-t/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/wojtek-t/subscriptions",
      "type": "User",
      "url": "https://api.github.com/users/wojtek-t"
    }
  ],
  "author_association": "CONTRIBUTOR",
  "body": "https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubernetes-e2e-gke-large-cluster/144/\n\nMultiple broken tests:\n\nFailed: [k8s.io] Services should be able to change the type and ports of a service [Slow] {Kubernetes e2e suite}\n\n```\n/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/service.go:791\nOct 23 18:09:27.001: Timeout waiting for service \"mutability-test\" to have a load balancer\n/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/service.go:2312\n```\n\nIssues about this test specifically: #26134\n\nFailed: [k8s.io] Networking [k8s.io] Granular Checks: Services [Slow] should update endpoints: udp {Kubernetes e2e suite}\n\n```\n/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/networking.go:163\nExpected error:\n    <*errors.StatusError | 0xc422a63980>: {\n        ErrStatus: {\n            TypeMeta: {Kind: \"\", APIVersion: \"\"},\n            ListMeta: {SelfLink: \"\", ResourceVersion: \"\"},\n            Status: \"Failure\",\n            Message: \"the server has received too many requests and has asked us to try again later (get pods netserver-12)\",\n            Reason: \"Timeout\",\n            Details: {\n                Name: \"netserver-12\",\n                Group: \"\",\n                Kind: \"pods\",\n                Causes: [\n                    {\n                        Type: \"UnexpectedServerResponse\",\n                        Message: \"Too many requests, please try again later.\",\n                        Field: \"\",\n                    },\n                ],\n                RetryAfterSeconds: 1,\n            },\n            Code: 429,\n        },\n    }\n    the server has received too many requests and has asked us to try again later (get pods netserver-12)\nnot to have occurred\n/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/networking_utils.go:511\n```\n\nIssues about this test specifically: #34250\n\nFailed: [k8s.io] Networking [k8s.io] Granular Checks: Services [Slow] should function for endpoint-Service: udp {Kubernetes e2e suite}\n\n```\n/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/networking.go:141\nfailed to get pod\nExpected error:\n    <*errors.StatusError | 0xc422a7a400>: {\n        ErrStatus: {\n            TypeMeta: {Kind: \"\", APIVersion: \"\"},\n            ListMeta: {SelfLink: \"\", ResourceVersion: \"\"},\n            Status: \"Failure\",\n            Message: \"the server has received too many requests and has asked us to try again later (get pods host-test-container-pod)\",\n            Reason: \"Timeout\",\n            Details: {\n                Name: \"host-test-container-pod\",\n                Group: \"\",\n                Kind: \"pods\",\n                Causes: [\n                    {\n                        Type: \"UnexpectedServerResponse\",\n                        Message: \"Too many requests, please try again later.\",\n                        Field: \"\",\n                    },\n                ],\n                RetryAfterSeconds: 1,\n            },\n            Code: 429,\n        },\n    }\n    the server has received too many requests and has asked us to try again later (get pods host-test-container-pod)\nnot to have occurred\n/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/exec_util.go:82\n```\n\nIssues about this test specifically: #34064\n\nFailed: [k8s.io] Probing container with readiness probe that fails should never be ready and never restart [Conformance] {Kubernetes e2e suite}\n\n```\n/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/common/container_probe.go:94\nFailed after 32.221s.\npod should not be ready\nError: Unexpected non-nil/non-zero extra argument at index 1:\n    <*errors.StatusError>: &errors.StatusError{ErrStatus:unversioned.Status{TypeMeta:unversioned.TypeMeta{Kind:\"\", APIVersion:\"\"}, ListMeta:unversioned.ListMeta{SelfLink:\"\", ResourceVersion:\"\"}, Status:\"Failure\", Message:\"the server has received too many requests and has asked us to try again later (get pods test-webserver-7466c6b3-9986-11e6-ad6e-0242ac110006)\", Reason:\"Timeout\", Details:(*unversioned.StatusDetails)(0xc422989220), Code:429}}\n/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/common/container_probe.go:84\n```\n\nIssues about this test specifically: #28084\n\nFailed: [k8s.io] Pods should cap back-off at MaxContainerBackOff [Slow] {Kubernetes e2e suite}\n\n```\n/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/common/pods.go:659\ngetting pod back-off-cap\nExpected error:\n    <*errors.StatusError | 0xc420231300>: {\n        ErrStatus: {\n            TypeMeta: {Kind: \"\", APIVersion: \"\"},\n            ListMeta: {SelfLink: \"\", ResourceVersion: \"\"},\n            Status: \"Failure\",\n            Message: \"the server has received too many requests and has asked us to try again later (get pods back-off-cap)\",\n            Reason: \"Timeout\",\n            Details: {\n                Name: \"back-off-cap\",\n                Group: \"\",\n                Kind: \"pods\",\n                Causes: [\n                    {\n                        Type: \"UnexpectedServerResponse\",\n                        Message: \"Too many requests, please try again later.\",\n                        Field: \"\",\n                    },\n                ],\n                RetryAfterSeconds: 1,\n            },\n            Code: 429,\n        },\n    }\n    the server has received too many requests and has asked us to try again later (get pods back-off-cap)\nnot to have occurred\n/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/common/pods.go:104\n```\n\nIssues about this test specifically: #27703 #32981 #35286\n\nPrevious issues for this suite: #34194\n",
  "closed_at": "2016-11-09T17:27:03Z",
  "closed_by": {
    "avatar_url": "https://avatars0.githubusercontent.com/u/13653959?v=4",
    "events_url": "https://api.github.com/users/k8s-github-robot/events{/privacy}",
    "followers_url": "https://api.github.com/users/k8s-github-robot/followers",
    "following_url": "https://api.github.com/users/k8s-github-robot/following{/other_user}",
    "gists_url": "https://api.github.com/users/k8s-github-robot/gists{/gist_id}",
    "gravatar_id": "",
    "html_url": "https://github.com/k8s-github-robot",
    "id": 13653959,
    "login": "k8s-github-robot",
    "node_id": "MDQ6VXNlcjEzNjUzOTU5",
    "organizations_url": "https://api.github.com/users/k8s-github-robot/orgs",
    "received_events_url": "https://api.github.com/users/k8s-github-robot/received_events",
    "repos_url": "https://api.github.com/users/k8s-github-robot/repos",
    "site_admin": false,
    "starred_url": "https://api.github.com/users/k8s-github-robot/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/k8s-github-robot/subscriptions",
    "type": "User",
    "url": "https://api.github.com/users/k8s-github-robot"
  },
  "comments": 1,
  "comments_url": "https://api.github.com/repos/kubernetes/kubernetes/issues/35402/comments",
  "created_at": "2016-10-24T03:23:20Z",
  "events_url": "https://api.github.com/repos/kubernetes/kubernetes/issues/35402/events",
  "html_url": "https://github.com/kubernetes/kubernetes/issues/35402",
  "id": 184741129,
  "labels": [
    {
      "color": "f7c6c7",
      "default": false,
      "description": "Categorizes issue or PR as related to a flaky test.",
      "id": 264749912,
      "name": "kind/flake",
      "node_id": "MDU6TGFiZWwyNjQ3NDk5MTI=",
      "url": "https://api.github.com/repos/kubernetes/kubernetes/labels/kind/flake"
    },
    {
      "color": "fbca04",
      "default": false,
      "description": "Higher priority than priority/awaiting-more-evidence.",
      "id": 114528273,
      "name": "priority/backlog",
      "node_id": "MDU6TGFiZWwxMTQ1MjgyNzM=",
      "url": "https://api.github.com/repos/kubernetes/kubernetes/labels/priority/backlog"
    }
  ],
  "labels_url": "https://api.github.com/repos/kubernetes/kubernetes/issues/35402/labels{/name}",
  "locked": false,
  "milestone": null,
  "node_id": "MDU6SXNzdWUxODQ3NDExMjk=",
  "number": 35402,
  "performed_via_github_app": null,
  "repository_url": "https://api.github.com/repos/kubernetes/kubernetes",
  "state": "closed",
  "title": "kubernetes-e2e-gke-large-cluster: broken test run",
  "updated_at": "2016-11-09T17:27:03Z",
  "url": "https://api.github.com/repos/kubernetes/kubernetes/issues/35402",
  "user": {
    "avatar_url": "https://avatars0.githubusercontent.com/u/13653959?v=4",
    "events_url": "https://api.github.com/users/k8s-github-robot/events{/privacy}",
    "followers_url": "https://api.github.com/users/k8s-github-robot/followers",
    "following_url": "https://api.github.com/users/k8s-github-robot/following{/other_user}",
    "gists_url": "https://api.github.com/users/k8s-github-robot/gists{/gist_id}",
    "gravatar_id": "",
    "html_url": "https://github.com/k8s-github-robot",
    "id": 13653959,
    "login": "k8s-github-robot",
    "node_id": "MDQ6VXNlcjEzNjUzOTU5",
    "organizations_url": "https://api.github.com/users/k8s-github-robot/orgs",
    "received_events_url": "https://api.github.com/users/k8s-github-robot/received_events",
    "repos_url": "https://api.github.com/users/k8s-github-robot/repos",
    "site_admin": false,
    "starred_url": "https://api.github.com/users/k8s-github-robot/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/k8s-github-robot/subscriptions",
    "type": "User",
    "url": "https://api.github.com/users/k8s-github-robot"
  }
}