{
  "active_lock_reason": null,
  "assignee": {
    "avatar_url": "https://avatars3.githubusercontent.com/u/567897?v=4",
    "events_url": "https://api.github.com/users/justaugustus/events{/privacy}",
    "followers_url": "https://api.github.com/users/justaugustus/followers",
    "following_url": "https://api.github.com/users/justaugustus/following{/other_user}",
    "gists_url": "https://api.github.com/users/justaugustus/gists{/gist_id}",
    "gravatar_id": "",
    "html_url": "https://github.com/justaugustus",
    "id": 567897,
    "login": "justaugustus",
    "node_id": "MDQ6VXNlcjU2Nzg5Nw==",
    "organizations_url": "https://api.github.com/users/justaugustus/orgs",
    "received_events_url": "https://api.github.com/users/justaugustus/received_events",
    "repos_url": "https://api.github.com/users/justaugustus/repos",
    "site_admin": false,
    "starred_url": "https://api.github.com/users/justaugustus/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/justaugustus/subscriptions",
    "type": "User",
    "url": "https://api.github.com/users/justaugustus"
  },
  "assignees": [
    {
      "avatar_url": "https://avatars3.githubusercontent.com/u/567897?v=4",
      "events_url": "https://api.github.com/users/justaugustus/events{/privacy}",
      "followers_url": "https://api.github.com/users/justaugustus/followers",
      "following_url": "https://api.github.com/users/justaugustus/following{/other_user}",
      "gists_url": "https://api.github.com/users/justaugustus/gists{/gist_id}",
      "gravatar_id": "",
      "html_url": "https://github.com/justaugustus",
      "id": 567897,
      "login": "justaugustus",
      "node_id": "MDQ6VXNlcjU2Nzg5Nw==",
      "organizations_url": "https://api.github.com/users/justaugustus/orgs",
      "received_events_url": "https://api.github.com/users/justaugustus/received_events",
      "repos_url": "https://api.github.com/users/justaugustus/repos",
      "site_admin": false,
      "starred_url": "https://api.github.com/users/justaugustus/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/justaugustus/subscriptions",
      "type": "User",
      "url": "https://api.github.com/users/justaugustus"
    }
  ],
  "author_association": "CONTRIBUTOR",
  "body": "<!-- Please use this template while reporting a bug and provide as much info as possible. Not doing so may result in your bug not being addressed in a timely manner. Thanks!\r\n\r\nIf the matter is security related, please disclose it privately via https://kubernetes.io/security/\r\n-->\r\n\r\n\r\n**What happened**:\r\nkube-proxy v1.16.11 fails to execute iptables-restore:\r\n```\r\n{\"log\":\"I0618 15:35:56.843819       1 service.go:373] Adding new service port \\\"kube-system/kube-dns:dns\\\" at 10.223.0.10:53/UDP\\n\",\"stream\":\"stderr\",\"time\":\"2020-06-18T15:35:56.844167118Z\"}\r\n{\"log\":\"I0618 15:35:56.843832       1 service.go:373] Adding new service port \\\"kube-system/calico-typha:calico-typha\\\" at 10.223.28.54:5473/TCP\\n\",\"stream\":\"stderr\",\"time\":\"2020-06-18T15:35:56.844172318Z\"}\r\n{\"log\":\"I0618 15:35:56.843844       1 service.go:373] Adding new service port \\\"default/kubernetes:https\\\" at 10.223.0.1:443/TCP\\n\",\"stream\":\"stderr\",\"time\":\"2020-06-18T15:35:56.844176518Z\"}\r\n{\"log\":\"I0618 15:35:56.843857       1 service.go:373] Adding new service port \\\"kube-system/allow-udp-egress:dummy\\\" at 10.223.112.137:1234/UDP\\n\",\"stream\":\"stderr\",\"time\":\"2020-06-18T15:35:56.844181318Z\"}\r\n{\"log\":\"I0618 15:35:56.843876       1 service.go:373] Adding new service port \\\"kube-system/metrics-server:\\\" at 10.223.80.184:443/TCP\\n\",\"stream\":\"stderr\",\"time\":\"2020-06-18T15:35:56.844305721Z\"}\r\n{\"log\":\"I0618 15:35:56.843890       1 service.go:373] Adding new service port \\\"kube-system/vpn-shoot:openvpn\\\" at 10.223.86.14:4314/TCP\\n\",\"stream\":\"stderr\",\"time\":\"2020-06-18T15:35:56.844312221Z\"}\r\n{\"log\":\"I0618 15:35:57.102753       1 proxier.go:1519] Opened local port \\\"nodePort for kube-system/vpn-shoot:openvpn\\\" (:32175/tcp)\\n\",\"stream\":\"stderr\",\"time\":\"2020-06-18T15:35:57.111034942Z\"}\r\n{\"log\":\"I0618 15:35:57.102963       1 proxier.go:1519] Opened local port \\\"nodePort for kube-system/allow-udp-egress:dummy\\\" (:31061/udp)\\n\",\"stream\":\"stderr\",\"time\":\"2020-06-18T15:35:57.111055742Z\"}\r\n{\"log\":\"I0618 15:42:28.998132       1 proxier.go:700] Stale udp service kube-system/kube-dns:dns -\\u003e 10.223.0.10\\n\",\"stream\":\"stderr\",\"time\":\"2020-06-18T15:42:28.998299797Z\"}\r\n{\"log\":\"E0618 15:42:29.040884       1 proxier.go:1418] Failed to execute iptables-restore: exit status 2 (iptables-restore v1.8.2 (nf_tables): Chain 'KUBE-MARK-DROP' does not exist\\n\",\"stream\":\"stderr\",\"time\":\"2020-06-18T15:42:29.041041355Z\"}\r\n{\"log\":\"Error occurred at line: 49\\n\",\"stream\":\"stderr\",\"time\":\"2020-06-18T15:42:29.041079457Z\"}\r\n{\"log\":\"Try `iptables-restore -h' or 'iptables-restore --help' for more information.\\n\",\"stream\":\"stderr\",\"time\":\"2020-06-18T15:42:29.041096658Z\"}\r\n{\"log\":\")\\n\",\"stream\":\"stderr\",\"time\":\"2020-06-18T15:42:29.041102958Z\"}\r\n{\"log\":\"I0618 15:42:29.040966       1 proxier.go:1421] Closing local ports after iptables-restore failure\\n\",\"stream\":\"stderr\",\"time\":\"2020-06-18T15:42:29.041111559Z\"}\r\n{\"log\":\"E0618 15:42:59.080751       1 proxier.go:1418] Failed to execute iptables-restore: exit status 2 (iptables-restore v1.8.2 (nf_tables): Chain 'KUBE-MARK-DROP' does not exist\\n\",\"stream\":\"stderr\",\"time\":\"2020-06-18T15:42:59.080906449Z\"}\r\n{\"log\":\"Error occurred at line: 49\\n\",\"stream\":\"stderr\",\"time\":\"2020-06-18T15:42:59.080971252Z\"}\r\n{\"log\":\"Try `iptables-restore -h' or 'iptables-restore --help' for more information.\\n\",\"stream\":\"stderr\",\"time\":\"2020-06-18T15:42:59.080979052Z\"}\r\n{\"log\":\")\\n\",\"stream\":\"stderr\",\"time\":\"2020-06-18T15:42:59.080984652Z\"}\r\n{\"log\":\"I0618 15:42:59.080904       1 proxier.go:1421] Closing local ports after iptables-restore failure\\n\",\"stream\":\"stderr\",\"time\":\"2020-06-18T15:42:59.081031354Z\"}\r\n{\"log\":\"E0618 15:43:29.122880       1 proxier.go:1418] Failed to execute iptables-restore: exit status 2 (iptables-restore v1.8.2 (nf_tables): Chain 'KUBE-MARK-DROP' does not exist\\n\",\"stream\":\"stderr\",\"time\":\"2020-06-18T15:43:29.123043015Z\"}\r\n{\"log\":\"Error occurred at line: 70\\n\",\"stream\":\"stderr\",\"time\":\"2020-06-18T15:43:29.123079817Z\"}\r\n{\"log\":\"Try `iptables-restore -h' or 'iptables-restore --help' for more information.\\n\",\"stream\":\"stderr\",\"time\":\"2020-06-18T15:43:29.123084317Z\"}\r\n{\"log\":\")\\n\",\"stream\":\"stderr\",\"time\":\"2020-06-18T15:43:29.123087817Z\"}\r\n{\"log\":\"I0618 15:43:29.123121       1 proxier.go:1421] Closing local ports after iptables-restore failure\\n\",\"stream\":\"stderr\",\"time\":\"2020-06-18T15:43:29.123202822Z\"}\r\n{\"log\":\"E0618 15:43:59.165741       1 proxier.go:1418] Failed to execute iptables-restore: exit status 2 (iptables-restore v1.8.2 (nf_tables): Chain 'KUBE-MARK-DROP' does not exist\\n\",\"stream\":\"stderr\",\"time\":\"2020-06-18T15:43:59.165944043Z\"}\r\n{\"log\":\"Error occurred at line: 44\\n\",\"stream\":\"stderr\",\"time\":\"2020-06-18T15:43:59.165977044Z\"}\r\n{\"log\":\"Try `iptables-restore -h' or 'iptables-restore --help' for more information.\\n\",\"stream\":\"stderr\",\"time\":\"2020-06-18T15:43:59.165984044Z\"}\r\n{\"log\":\")\\n\",\"stream\":\"stderr\",\"time\":\"2020-06-18T15:43:59.165989644Z\"}\r\n{\"log\":\"I0618 15:43:59.165841       1 proxier.go:1421] Closing local ports after iptables-restore failure\\n\",\"stream\":\"stderr\",\"time\":\"2020-06-18T15:43:59.165995045Z\"}\r\n{\"log\":\"E0618 15:44:29.215236       1 proxier.go:1418] Failed to execute iptables-restore: exit status 2 (iptables-restore v1.8.2 (nf_tables): Chain 'KUBE-MARK-DROP' does not exist\\n\",\"stream\":\"stderr\",\"time\":\"2020-06-18T15:44:29.21548492Z\"}\r\n{\"log\":\"Error occurred at line: 49\\n\",\"stream\":\"stderr\",\"time\":\"2020-06-18T15:44:29.215525921Z\"}\r\n{\"log\":\"Try `iptables-restore -h' or 'iptables-restore --help' for more information.\\n\",\"stream\":\"stderr\",\"time\":\"2020-06-18T15:44:29.215532021Z\"}\r\n{\"log\":\")\\n\",\"stream\":\"stderr\",\"time\":\"2020-06-18T15:44:29.215561822Z\"}\r\n{\"log\":\"I0618 15:44:29.215337       1 proxier.go:1421] Closing local ports after iptables-restore failure\\n\",\"stream\":\"stderr\",\"time\":\"2020-06-18T15:44:29.215566623Z\"}\r\n{\"log\":\"E0618 15:44:59.259447       1 proxier.go:1418] Failed to execute iptables-restore: exit status 2 (iptables-restore v1.8.2 (nf_tables): Chain 'KUBE-MARK-DROP' does not exist\\n\",\"stream\":\"stderr\",\"time\":\"2020-06-18T15:44:59.259569268Z\"}\r\n```\r\n\r\nThe same setup work perfectly fine with kube-proxy v1.16.10.\r\n\r\n**What you expected to happen**:\r\nkube-proxy to be able to execute iptables-restore.\r\n\r\n**How to reproduce it (as minimally and precisely as possible)**:\r\n\r\n**Anything else we need to know?**:\r\n\r\n**Environment**:\r\n- Kubernetes version (use `kubectl version`):\r\n```\r\n$ k version\r\nClient Version: version.Info{Major:\"1\", Minor:\"18\", GitVersion:\"v1.18.3\", GitCommit:\"2e7996e3e2712684bc73f0dec0200d64eec7fe40\", GitTreeState:\"clean\", BuildDate:\"2020-05-21T14:51:23Z\", GoVersion:\"go1.14.3\", Compiler:\"gc\", Platform:\"darwin/amd64\"}\r\nServer Version: version.Info{Major:\"1\", Minor:\"16\", GitVersion:\"v1.16.11\", GitCommit:\"436254b798f772bcb8e67dcfe122e46500eeb254\", GitTreeState:\"clean\", BuildDate:\"2020-06-17T11:41:28Z\", GoVersion:\"go1.13.9\", Compiler:\"gc\", Platform:\"linux/amd64\"}\r\n```\r\n\r\n- Cloud provider or hardware configuration:\r\n- OS (e.g: `cat /etc/os-release`):\r\n\r\n```\r\n# cat /etc/os-release\r\nNAME=\"Container Linux by CoreOS\"\r\nID=coreos\r\nVERSION=2303.3.0\r\nVERSION_ID=2303.3.0\r\nBUILD_ID=2019-12-02-2049\r\nPRETTY_NAME=\"Container Linux by CoreOS 2303.3.0 (Rhyolite)\"\r\nANSI_COLOR=\"38;5;75\"\r\nHOME_URL=\"https://coreos.com/\"\r\nBUG_REPORT_URL=\"https://issues.coreos.com\"\r\nCOREOS_BOARD=\"amd64-usr\"\r\n```\r\n\r\n- Kernel (e.g. `uname -a`):\r\n```\r\n# uname -a\r\nLinux foo 4.19.86-coreos #1 SMP Mon Dec 2 20:13:38 -00 2019 x86_64 Intel(R) Xeon(R) Platinum 8171M CPU @ 2.60GHz GenuineIntel GNU/Linux\r\n```\r\n\r\n- Install tools:\r\n- Network plugin and version (if this is a network-related bug): Calico v3.13.4\r\n- Others:\r\n",
  "closed_at": "2020-06-26T20:06:33Z",
  "closed_by": {
    "avatar_url": "https://avatars0.githubusercontent.com/u/20407524?v=4",
    "events_url": "https://api.github.com/users/k8s-ci-robot/events{/privacy}",
    "followers_url": "https://api.github.com/users/k8s-ci-robot/followers",
    "following_url": "https://api.github.com/users/k8s-ci-robot/following{/other_user}",
    "gists_url": "https://api.github.com/users/k8s-ci-robot/gists{/gist_id}",
    "gravatar_id": "",
    "html_url": "https://github.com/k8s-ci-robot",
    "id": 20407524,
    "login": "k8s-ci-robot",
    "node_id": "MDQ6VXNlcjIwNDA3NTI0",
    "organizations_url": "https://api.github.com/users/k8s-ci-robot/orgs",
    "received_events_url": "https://api.github.com/users/k8s-ci-robot/received_events",
    "repos_url": "https://api.github.com/users/k8s-ci-robot/repos",
    "site_admin": false,
    "starred_url": "https://api.github.com/users/k8s-ci-robot/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/k8s-ci-robot/subscriptions",
    "type": "User",
    "url": "https://api.github.com/users/k8s-ci-robot"
  },
  "comments": 22,
  "comments_url": "https://api.github.com/repos/kubernetes/kubernetes/issues/92275/comments",
  "created_at": "2020-06-18T22:58:48Z",
  "events_url": "https://api.github.com/repos/kubernetes/kubernetes/issues/92275/events",
  "html_url": "https://github.com/kubernetes/kubernetes/issues/92275",
  "id": 641596601,
  "labels": [
    {
      "color": "0052cc",
      "default": false,
      "description": "Issues or PRs related to the hyperkube subproject",
      "id": 1193551502,
      "name": "area/hyperkube",
      "node_id": "MDU6TGFiZWwxMTkzNTUxNTAy",
      "url": "https://api.github.com/repos/kubernetes/kubernetes/labels/area/hyperkube"
    },
    {
      "color": "0052cc",
      "default": false,
      "description": "Issues or PRs related to the Release Engineering subproject",
      "id": 268190668,
      "name": "area/release-eng",
      "node_id": "MDU6TGFiZWwyNjgxOTA2Njg=",
      "url": "https://api.github.com/repos/kubernetes/kubernetes/labels/area/release-eng"
    },
    {
      "color": "e11d21",
      "default": false,
      "description": "Categorizes issue or PR as related to a bug.",
      "id": 105146071,
      "name": "kind/bug",
      "node_id": "MDU6TGFiZWwxMDUxNDYwNzE=",
      "url": "https://api.github.com/repos/kubernetes/kubernetes/labels/kind/bug"
    },
    {
      "color": "e11d21",
      "default": false,
      "description": "Categorizes issue or PR as related to a regression from a prior release.",
      "id": 1967276560,
      "name": "kind/regression",
      "node_id": "MDU6TGFiZWwxOTY3Mjc2NTYw",
      "url": "https://api.github.com/repos/kubernetes/kubernetes/labels/kind/regression"
    },
    {
      "color": "e11d21",
      "default": false,
      "description": "Highest priority. Must be actively worked on as someone's top priority right now.",
      "id": 114528068,
      "name": "priority/critical-urgent",
      "node_id": "MDU6TGFiZWwxMTQ1MjgwNjg=",
      "url": "https://api.github.com/repos/kubernetes/kubernetes/labels/priority/critical-urgent"
    },
    {
      "color": "d2b48c",
      "default": false,
      "description": "Categorizes an issue or PR as relevant to SIG Network.",
      "id": 116712108,
      "name": "sig/network",
      "node_id": "MDU6TGFiZWwxMTY3MTIxMDg=",
      "url": "https://api.github.com/repos/kubernetes/kubernetes/labels/sig/network"
    },
    {
      "color": "d2b48c",
      "default": false,
      "description": "Categorizes an issue or PR as relevant to SIG Release.",
      "id": 614023989,
      "name": "sig/release",
      "node_id": "MDU6TGFiZWw2MTQwMjM5ODk=",
      "url": "https://api.github.com/repos/kubernetes/kubernetes/labels/sig/release"
    },
    {
      "color": "d455d0",
      "default": false,
      "description": "Indicates an issue that can not or will not be resolved.",
      "id": 862108765,
      "name": "triage/unresolved",
      "node_id": "MDU6TGFiZWw4NjIxMDg3NjU=",
      "url": "https://api.github.com/repos/kubernetes/kubernetes/labels/triage/unresolved"
    }
  ],
  "labels_url": "https://api.github.com/repos/kubernetes/kubernetes/issues/92275/labels{/name}",
  "locked": false,
  "milestone": null,
  "node_id": "MDU6SXNzdWU2NDE1OTY2MDE=",
  "number": 92275,
  "performed_via_github_app": null,
  "repository_url": "https://api.github.com/repos/kubernetes/kubernetes",
  "state": "closed",
  "title": "hypekube kube-proxy: Chain 'KUBE-MARK-DROP' does not exist",
  "updated_at": "2020-07-10T10:33:33Z",
  "url": "https://api.github.com/repos/kubernetes/kubernetes/issues/92275",
  "user": {
    "avatar_url": "https://avatars2.githubusercontent.com/u/9372594?v=4",
    "events_url": "https://api.github.com/users/ialidzhikov/events{/privacy}",
    "followers_url": "https://api.github.com/users/ialidzhikov/followers",
    "following_url": "https://api.github.com/users/ialidzhikov/following{/other_user}",
    "gists_url": "https://api.github.com/users/ialidzhikov/gists{/gist_id}",
    "gravatar_id": "",
    "html_url": "https://github.com/ialidzhikov",
    "id": 9372594,
    "login": "ialidzhikov",
    "node_id": "MDQ6VXNlcjkzNzI1OTQ=",
    "organizations_url": "https://api.github.com/users/ialidzhikov/orgs",
    "received_events_url": "https://api.github.com/users/ialidzhikov/received_events",
    "repos_url": "https://api.github.com/users/ialidzhikov/repos",
    "site_admin": false,
    "starred_url": "https://api.github.com/users/ialidzhikov/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/ialidzhikov/subscriptions",
    "type": "User",
    "url": "https://api.github.com/users/ialidzhikov"
  }
}