{
  "active_lock_reason": null,
  "assignee": {
    "avatar_url": "https://avatars1.githubusercontent.com/u/4178417?v=4",
    "events_url": "https://api.github.com/users/andyzhangx/events{/privacy}",
    "followers_url": "https://api.github.com/users/andyzhangx/followers",
    "following_url": "https://api.github.com/users/andyzhangx/following{/other_user}",
    "gists_url": "https://api.github.com/users/andyzhangx/gists{/gist_id}",
    "gravatar_id": "",
    "html_url": "https://github.com/andyzhangx",
    "id": 4178417,
    "login": "andyzhangx",
    "node_id": "MDQ6VXNlcjQxNzg0MTc=",
    "organizations_url": "https://api.github.com/users/andyzhangx/orgs",
    "received_events_url": "https://api.github.com/users/andyzhangx/received_events",
    "repos_url": "https://api.github.com/users/andyzhangx/repos",
    "site_admin": false,
    "starred_url": "https://api.github.com/users/andyzhangx/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/andyzhangx/subscriptions",
    "type": "User",
    "url": "https://api.github.com/users/andyzhangx"
  },
  "assignees": [
    {
      "avatar_url": "https://avatars1.githubusercontent.com/u/4178417?v=4",
      "events_url": "https://api.github.com/users/andyzhangx/events{/privacy}",
      "followers_url": "https://api.github.com/users/andyzhangx/followers",
      "following_url": "https://api.github.com/users/andyzhangx/following{/other_user}",
      "gists_url": "https://api.github.com/users/andyzhangx/gists{/gist_id}",
      "gravatar_id": "",
      "html_url": "https://github.com/andyzhangx",
      "id": 4178417,
      "login": "andyzhangx",
      "node_id": "MDQ6VXNlcjQxNzg0MTc=",
      "organizations_url": "https://api.github.com/users/andyzhangx/orgs",
      "received_events_url": "https://api.github.com/users/andyzhangx/received_events",
      "repos_url": "https://api.github.com/users/andyzhangx/repos",
      "site_admin": false,
      "starred_url": "https://api.github.com/users/andyzhangx/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/andyzhangx/subscriptions",
      "type": "User",
      "url": "https://api.github.com/users/andyzhangx"
    }
  ],
  "author_association": "CONTRIBUTOR",
  "body": "**What happened**:\r\n\r\n#78298 made sure that API calls to Azure that return a HTTP code 200 with an embedded error are retried. Nevertheless, we observe a series of errors during the Azure Disk detach backoff while calling `processHTTPRetryResponse()`, and the detach operation is immediately cancelled.\r\n\r\n**Happy scenario: the disk is to be re-attached to the same VM.**\r\nThe reconciler's `attacherDetacher.AttachVolume` will update the VMSS instance and the previous detach error will be masked. It takes 15 min for the detach call to timeout but the disk will eventually get re-attached after several VMSS updates (`azure_controller_vmss.go:87] azureDisk - update(<vmss>): vm(<vm>) - attach disk(<disk>)`).\r\n\r\n**Not-so-happy scenario: the disk is to be re-attached to another VM.**\r\nThe same errors as in #78172 will be thrown indefinitely.\r\n\r\ncontroller-manager's logs:\r\n```\r\n# detach routine starts detaching the disk\r\n\r\nI0603 16:44:01.823620       1 reconciler.go:229] attacherDetacher.DetachVolume started for volume \"pvc-db8323f9-1eb5-11e9-882a-000d3a1f73e7\" (UniqueName: \"kubernetes.io/azure-disk//subscriptions/<subs>/resourceGroups/cacl2-cust-d1/providers/Microsoft.Compute/disks/k8s-mstr-cacl2-cust-d1-kub-d-pvc-db8323f9-1eb5-11e9-882a-000d3a1f73e7\") on node \"k8s-cust-79105490-vmss00004o\" \r\nI0603 16:44:01.839835       1 operation_generator.go:1221] Verified volume is safe to detach for volume \"pvc-db8323f9-1eb5-11e9-882a-000d3a1f73e7\" (UniqueName: \"kubernetes.io/azure-disk//subscriptions/<subs>/resourceGroups/cacl2-cust-d1/providers/Microsoft.Compute/disks/k8s-mstr-cacl2-cust-d1-kub-d-pvc-db8323f9-1eb5-11e9-882a-000d3a1f73e7\") on node \"k8s-cust-79105490-vmss00004o\" \r\nI0603 16:44:01.847198       1 azure_controller_vmss.go:122] azureDisk - detach disk: name \"\" uri \"/subscriptions/<subs>/resourceGroups/cacl2-cust-d1/providers/Microsoft.Compute/disks/k8s-mstr-cacl2-cust-d1-kub-d-pvc-db8323f9-1eb5-11e9-882a-000d3a1f73e7\"\r\nI0603 16:44:01.847322       1 azure_controller_vmss.go:151] azureDisk - update(cacl2-cust-d1): vm(k8s-cust-79105490-vmss00004o) - detach disk(, /subscriptions/<subs>/resourceGroups/cacl2-cust-d1/providers/Microsoft.Compute/disks/k8s-mstr-cacl2-cust-d1-kub-d-pvc-db8323f9-1eb5-11e9-882a-000d3a1f73e7)\r\n\r\n# another background routine determines the disk is \"Unattached\"\r\n\r\nI0603 16:45:36.478028       1 attacher.go:145] azureDisk - VolumesAreAttached: check volume \"k8s-mstr-cacl2-cust-d1-kub-d-pvc-db8323f9-1eb5-11e9-882a-000d3a1f73e7\" (specName: \"pvc-db8323f9-1eb5-11e9-882a-000d3a1f73e7\") is no longer attached\r\nI0603 16:45:36.478066       1 operation_generator.go:193] VerifyVolumesAreAttached determined volume \"kubernetes.io/azure-disk//subscriptions/<subs>/resourceGroups/cacl2-cust-d1/providers/Microsoft.Compute/disks/k8s-mstr-cacl2-cust-d1-kub-d-pvc-db8323f9-1eb5-11e9-882a-000d3a1f73e7\" (spec.Name: \"pvc-db8323f9-1eb5-11e9-882a-000d3a1f73e7\") is no longer attached to node \"k8s-cust-79105490-vmss00004o\", therefore it was marked as detached.\r\n\r\n# detach routine times out after 15 min, but API returns 200\r\n\r\nI0603 16:59:02.523206       1 azure_controller_common.go:115] azureDisk - update backing off: detach disk(, /subscriptions/<subs>/resourceGroups/cacl2-cust-d1/providers/Microsoft.Compute/disks/k8s-mstr-cacl2-cust-d1-kub-d-pvc-db8323f9-1eb5-11e9-882a-000d3a1f73e7), err: azure#WaitForCompletion: context has been cancelled: StatusCode=200 -- Original Error: context deadline exceeded\r\n\r\n# this is followed by a bunch of \"disk not found\" errors\r\n\r\nE0603 16:59:02.603427       1 azure_backoff.go:427] processHTTPRetryResponse: backoff failure, will retry, err=detach azure disk failure, disk  not found, diskURI: /subscriptions/<subs>/resourceGroups/cacl2-cust-d1/providers/Microsoft.Compute/disks/k8s-mstr-cacl2-cust-d1-kub-d-pvc-db8323f9-1eb5-11e9-882a-000d3a1f73e7\r\nE0603 16:59:12.008429       1 azure_backoff.go:427] processHTTPRetryResponse: backoff failure, will retry, err=detach azure disk failure, disk  not found, diskURI: /subscriptions/<subs>/resourceGroups/cacl2-cust-d1/providers/Microsoft.Compute/disks/k8s-mstr-cacl2-cust-d1-kub-d-pvc-db8323f9-1eb5-11e9-882a-000d3a1f73e7\r\nE0603 16:59:23.655154       1 azure_backoff.go:427] processHTTPRetryResponse: backoff failure, will retry, err=detach azure disk failure, disk  not found, diskURI: /subscriptions/<subs>/resourceGroups/cacl2-cust-d1/providers/Microsoft.Compute/disks/k8s-mstr-cacl2-cust-d1-kub-d-pvc-db8323f9-1eb5-11e9-882a-000d3a1f73e7\r\nE0603 16:59:40.085495       1 azure_backoff.go:427] processHTTPRetryResponse: backoff failure, will retry, err=detach azure disk failure, disk  not found, diskURI: /subscriptions/<subs>/resourceGroups/cacl2-cust-d1/providers/Microsoft.Compute/disks/k8s-mstr-cacl2-cust-d1-kub-d-pvc-db8323f9-1eb5-11e9-882a-000d3a1f73e7\r\nE0603 17:00:06.609956       1 azure_backoff.go:427] processHTTPRetryResponse: backoff failure, will retry, err=detach azure disk failure, disk  not found, diskURI: /subscriptions/<subs>/resourceGroups/cacl2-cust-d1/providers/Microsoft.Compute/disks/k8s-mstr-cacl2-cust-d1-kub-d-pvc-db8323f9-1eb5-11e9-882a-000d3a1f73e7\r\nE0603 17:00:49.698392       1 azure_backoff.go:427] processHTTPRetryResponse: backoff failure, will retry, err=detach azure disk failure, disk  not found, diskURI: /subscriptions/<subs>/resourceGroups/cacl2-cust-d1/providers/Microsoft.Compute/disks/k8s-mstr-cacl2-cust-d1-kub-d-pvc-db8323f9-1eb5-11e9-882a-000d3a1f73e7\r\nI0603 17:00:49.698449       1 azure_controller_common.go:122] azureDisk - update abort backoff: detach disk(, /subscriptions/<subs>/resourceGroups/cacl2-cust-d1/providers/Microsoft.Compute/disks/k8s-mstr-cacl2-cust-d1-kub-d-pvc-db8323f9-1eb5-11e9-882a-000d3a1f73e7), err: timed out waiting for the condition\r\nE0603 17:00:49.698473       1 azure_controller_common.go:126] azureDisk - detach disk(, /subscriptions/<subs>/resourceGroups/cacl2-cust-d1/providers/Microsoft.Compute/disks/k8s-mstr-cacl2-cust-d1-kub-d-pvc-db8323f9-1eb5-11e9-882a-000d3a1f73e7) failed, err: timed out waiting for the condition\r\nE0603 17:00:49.698490       1 attacher.go:302] failed to detach azure disk \"/subscriptions/<subs>/resourceGroups/cacl2-cust-d1/providers/Microsoft.Compute/disks/k8s-mstr-cacl2-cust-d1-kub-d-pvc-db8323f9-1eb5-11e9-882a-000d3a1f73e7\", err timed out waiting for the condition\r\nI0603 17:00:49.698531       1 attacher.go:305] azureDisk - disk:/subscriptions/<subs>/resourceGroups/cacl2-cust-d1/providers/Microsoft.Compute/disks/k8s-mstr-cacl2-cust-d1-kub-d-pvc-db8323f9-1eb5-11e9-882a-000d3a1f73e7 was detached from node:k8s-cust-79105490-vmss00004o\r\nE0603 17:00:49.698638       1 nestedpendingoperations.go:267] Operation for \"\\\"kubernetes.io/azure-disk//subscriptions/<subs>/resourceGroups/cacl2-cust-d1/providers/Microsoft.Compute/disks/k8s-mstr-cacl2-cust-d1-kub-d-pvc-db8323f9-1eb5-11e9-882a-000d3a1f73e7\\\"\" failed. No retries permitted until 2019-06-03 17:00:50.198578075 +0000 UTC m=+26367.031508457 (durationBeforeRetry 500ms). Error: \"DetachVolume.Detach failed for volume \\\"pvc-db8323f9-1eb5-11e9-882a-000d3a1f73e7\\\" (UniqueName: \\\"kubernetes.io/azure-disk//subscriptions/<subs>/resourceGroups/cacl2-cust-d1/providers/Microsoft.Compute/disks/k8s-mstr-cacl2-cust-d1-kub-d-pvc-db8323f9-1eb5-11e9-882a-000d3a1f73e7\\\") on node \\\"k8s-cust-79105490-vmss00004o\\\" : timed out waiting for the condition\"\r\n\r\n# attach volume fails with StatusCode=409 (see issue 78172) again and again\r\n# ...\r\n```\r\n\r\n**What you expected to happen**:\r\n\r\nThe backoff succeeds and the failed detach operation gets retried.\r\n\r\n**How to reproduce it**:\r\n\r\nA single Pod with a single Azure Disk.\r\nThis seems quite hard to reproduce, but it is happening consistently in one of our customer's resource group (eastus).\r\n\r\n**Anything else we need to know?**:\r\n\r\n**Environment**:\r\n- Kubernetes version: `release-1.12` branch (kubernetes/kubernetes@e94e2ecda3bb3e7a44205169693d7ab420b92035)\r\n- Cloud provider: Azure (via AKS-Engine)\r\n- OS: Ubuntu 16.04.6 LTS\r\n- Kernel: 4.15.0-1042-azure\r\n- Install tools: [aks-engine](https://github.com/Azure/aks-engine)\r\n- Network plugin and version:\r\n- Others:\r\n\r\n/sig azure\r\npaging @andyzhangx @feiskyer",
  "closed_at": "2019-06-07T12:12:01Z",
  "closed_by": {
    "avatar_url": "https://avatars0.githubusercontent.com/u/20407524?v=4",
    "events_url": "https://api.github.com/users/k8s-ci-robot/events{/privacy}",
    "followers_url": "https://api.github.com/users/k8s-ci-robot/followers",
    "following_url": "https://api.github.com/users/k8s-ci-robot/following{/other_user}",
    "gists_url": "https://api.github.com/users/k8s-ci-robot/gists{/gist_id}",
    "gravatar_id": "",
    "html_url": "https://github.com/k8s-ci-robot",
    "id": 20407524,
    "login": "k8s-ci-robot",
    "node_id": "MDQ6VXNlcjIwNDA3NTI0",
    "organizations_url": "https://api.github.com/users/k8s-ci-robot/orgs",
    "received_events_url": "https://api.github.com/users/k8s-ci-robot/received_events",
    "repos_url": "https://api.github.com/users/k8s-ci-robot/repos",
    "site_admin": false,
    "starred_url": "https://api.github.com/users/k8s-ci-robot/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/k8s-ci-robot/subscriptions",
    "type": "User",
    "url": "https://api.github.com/users/k8s-ci-robot"
  },
  "comments": 1,
  "comments_url": "https://api.github.com/repos/kubernetes/kubernetes/issues/78660/comments",
  "created_at": "2019-06-03T18:04:00Z",
  "events_url": "https://api.github.com/repos/kubernetes/kubernetes/issues/78660/events",
  "html_url": "https://github.com/kubernetes/kubernetes/issues/78660",
  "id": 451615547,
  "labels": [
    {
      "color": "e11d21",
      "default": false,
      "description": "Categorizes issue or PR as related to a bug.",
      "id": 105146071,
      "name": "kind/bug",
      "node_id": "MDU6TGFiZWwxMDUxNDYwNzE=",
      "url": "https://api.github.com/repos/kubernetes/kubernetes/labels/kind/bug"
    }
  ],
  "labels_url": "https://api.github.com/repos/kubernetes/kubernetes/issues/78660/labels{/name}",
  "locked": false,
  "milestone": null,
  "node_id": "MDU6SXNzdWU0NTE2MTU1NDc=",
  "number": 78660,
  "performed_via_github_app": null,
  "repository_url": "https://api.github.com/repos/kubernetes/kubernetes",
  "state": "closed",
  "title": "Azure Disk detach backoff cancelled due to error \"detach azure disk failure, disk  not found\"",
  "updated_at": "2019-06-07T12:12:01Z",
  "url": "https://api.github.com/repos/kubernetes/kubernetes/issues/78660",
  "user": {
    "avatar_url": "https://avatars2.githubusercontent.com/u/3299086?v=4",
    "events_url": "https://api.github.com/users/antoineco/events{/privacy}",
    "followers_url": "https://api.github.com/users/antoineco/followers",
    "following_url": "https://api.github.com/users/antoineco/following{/other_user}",
    "gists_url": "https://api.github.com/users/antoineco/gists{/gist_id}",
    "gravatar_id": "",
    "html_url": "https://github.com/antoineco",
    "id": 3299086,
    "login": "antoineco",
    "node_id": "MDQ6VXNlcjMyOTkwODY=",
    "organizations_url": "https://api.github.com/users/antoineco/orgs",
    "received_events_url": "https://api.github.com/users/antoineco/received_events",
    "repos_url": "https://api.github.com/users/antoineco/repos",
    "site_admin": false,
    "starred_url": "https://api.github.com/users/antoineco/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/antoineco/subscriptions",
    "type": "User",
    "url": "https://api.github.com/users/antoineco"
  }
}