{
  "active_lock_reason": null,
  "assignee": null,
  "assignees": [],
  "author_association": "MEMBER",
  "body": "**Is this a BUG REPORT or FEATURE REQUEST?**:\r\n/kind bug\r\n\r\n**What happened**:\r\nstart kubelet with `--enforce-node-allocatable=pods,kube-reserved,system-reserved` and without `--system-reserved`\r\ne.g.\r\n/usr/bin/kubelet --v=9 --address=0.0.0.0 --hostname-override=10.114.51.205 --kubeconfig=/etc/kubernetes/kubelet.kubeconfig --pod-manift-path=/etc/kubernetes/manifests --log-dir=/root/info/logs/k8s --fail-swap-on=false --cluster-dns=10.254.0.10 --cluster-domain=cluster.local --logtostderr=false --allow-privileged=true --kube-reserved=cpu=500m,memory=500Mi --image-gc-low-threshold=80 --image-gc-high-threshold=90 --kube-reserved-cgroup=/kubelet.service --system-reserved-cgroup=/system.slice --enforce-node-allocatable=pods,kube-reserved,system-reserved --cgroups-per-qos=true \r\n\r\nThe node is Ready, but log complaints: \r\n`E0607 16:05:02.971107 25854 runtime.go:66] Observed a panic: \"invalid memory address or nil pointer dereference\" (runtime error: invalid memory address or nil pointer dereference)` \r\n\r\nAnd the eviction_manager didn't start. \r\n\r\n**What you expected to happen**:\r\nThe log don't complaint errors and eviction_manager start successfully. \r\n\r\n**How to reproduce it (as minimally and precisely as possible)**:\r\nstart kubelet with `--enforce-node-allocatable=pods,kube-reserved,system-reserved` and without `--system-reserved`\r\n\r\n**Anything else we need to know?**:\r\nNONE\r\n\r\n**Environment**:\r\n- Kubernetes version (use `kubectl version`):1.10.0\r\n- Cloud provider or hardware configuration:\r\n- OS (e.g. from /etc/os-release):centos\r\n- Kernel (e.g. `uname -a`):\r\n- Install tools:\r\n- Others:\r\n",
  "closed_at": "2018-08-02T22:42:09Z",
  "closed_by": {
    "avatar_url": "https://avatars0.githubusercontent.com/u/13653959?v=4",
    "events_url": "https://api.github.com/users/k8s-github-robot/events{/privacy}",
    "followers_url": "https://api.github.com/users/k8s-github-robot/followers",
    "following_url": "https://api.github.com/users/k8s-github-robot/following{/other_user}",
    "gists_url": "https://api.github.com/users/k8s-github-robot/gists{/gist_id}",
    "gravatar_id": "",
    "html_url": "https://github.com/k8s-github-robot",
    "id": 13653959,
    "login": "k8s-github-robot",
    "node_id": "MDQ6VXNlcjEzNjUzOTU5",
    "organizations_url": "https://api.github.com/users/k8s-github-robot/orgs",
    "received_events_url": "https://api.github.com/users/k8s-github-robot/received_events",
    "repos_url": "https://api.github.com/users/k8s-github-robot/repos",
    "site_admin": false,
    "starred_url": "https://api.github.com/users/k8s-github-robot/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/k8s-github-robot/subscriptions",
    "type": "User",
    "url": "https://api.github.com/users/k8s-github-robot"
  },
  "comments": 3,
  "comments_url": "https://api.github.com/repos/kubernetes/kubernetes/issues/66189/comments",
  "created_at": "2018-07-14T02:30:37Z",
  "events_url": "https://api.github.com/repos/kubernetes/kubernetes/issues/66189/events",
  "html_url": "https://github.com/kubernetes/kubernetes/issues/66189",
  "id": 341201639,
  "labels": [
    {
      "color": "e11d21",
      "default": false,
      "description": "Categorizes issue or PR as related to a bug.",
      "id": 105146071,
      "name": "kind/bug",
      "node_id": "MDU6TGFiZWwxMDUxNDYwNzE=",
      "url": "https://api.github.com/repos/kubernetes/kubernetes/labels/kind/bug"
    },
    {
      "color": "d2b48c",
      "default": false,
      "description": "Categorizes an issue or PR as relevant to SIG Node.",
      "id": 173493665,
      "name": "sig/node",
      "node_id": "MDU6TGFiZWwxNzM0OTM2NjU=",
      "url": "https://api.github.com/repos/kubernetes/kubernetes/labels/sig/node"
    }
  ],
  "labels_url": "https://api.github.com/repos/kubernetes/kubernetes/issues/66189/labels{/name}",
  "locked": false,
  "milestone": null,
  "node_id": "MDU6SXNzdWUzNDEyMDE2Mzk=",
  "number": 66189,
  "performed_via_github_app": null,
  "repository_url": "https://api.github.com/repos/kubernetes/kubernetes",
  "state": "closed",
  "title": "eviction_manager didn't start with invalid kubelet flags",
  "updated_at": "2018-08-27T12:25:11Z",
  "url": "https://api.github.com/repos/kubernetes/kubernetes/issues/66189",
  "user": {
    "avatar_url": "https://avatars2.githubusercontent.com/u/23079251?v=4",
    "events_url": "https://api.github.com/users/linyouchong/events{/privacy}",
    "followers_url": "https://api.github.com/users/linyouchong/followers",
    "following_url": "https://api.github.com/users/linyouchong/following{/other_user}",
    "gists_url": "https://api.github.com/users/linyouchong/gists{/gist_id}",
    "gravatar_id": "",
    "html_url": "https://github.com/linyouchong",
    "id": 23079251,
    "login": "linyouchong",
    "node_id": "MDQ6VXNlcjIzMDc5MjUx",
    "organizations_url": "https://api.github.com/users/linyouchong/orgs",
    "received_events_url": "https://api.github.com/users/linyouchong/received_events",
    "repos_url": "https://api.github.com/users/linyouchong/repos",
    "site_admin": false,
    "starred_url": "https://api.github.com/users/linyouchong/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/linyouchong/subscriptions",
    "type": "User",
    "url": "https://api.github.com/users/linyouchong"
  }
}