{
  "active_lock_reason": null,
  "assignee": null,
  "assignees": [],
  "author_association": "MEMBER",
  "body": "<!-- This form is for bug reports and feature requests ONLY! \r\n\r\nIf you're looking for help check [Stack Overflow](https://stackoverflow.com/questions/tagged/kubernetes) and the [troubleshooting guide](https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/).\r\n-->\r\n\r\n**Is this a BUG REPORT or FEATURE REQUEST?**:\r\n\r\n/kind bug\r\n\r\n**What happened**:\r\nPod creation doesn't finish due to the following error. If the directory doesn't exist it will be created instead of returning error.\r\n```\r\nE0918 17:02:33.010764   47970 nestedpendingoperations.go:264] Operation for \"\\\"kubernetes.io/fc/[wwn]\\\"\" failed. No retries permitted until 2017-09-18 17:02:33.510731259 -0400 EDT (durationBeforeRetry 500ms). Error: MountVolume.WaitForAttach failed for volume \"pv0001\" (UniqueName: \"kubernetes.io/fc/[wwn]\") pod \"nginx-pod1\" (UID: \"ae61367d-9cb4-11e7-886d-f8bc12550954\") : Heuristic determination of mount point failed:stat /var/lib/kubelet/plugins/kubernetes.io/fc/<wwn>-lun-0: no such file or directory \r\nI0918 17:02:33.576630   47970 reconciler.go:257] operationExecutor.MountVolume started for volume \"pv0001\" (UniqueName: \"kubernetes.io/fc/[wwn]\") pod \"nginx-pod1\" (UID: \"ae61367d-9cb4-11e7-886d-f8bc12550954\")  \r\n```\r\n\r\n**What you expected to happen**:\r\n\r\nPod with FC volume works properly.\r\n\r\n**How to reproduce it (as minimally and precisely as possible)**:\r\n\r\n- Clean up under the \"/var/lib/kubelet/plugins\"\r\n- Create a Pod with FC volume\r\n\r\n**Environment**:\r\n- Kubernetes version (use `kubectl version`):\r\n```\r\nClient Version: version.Info{Major:\"1\", Minor:\"9+\", GitVersion:\"v1.9.0-alpha.0.723+8ca1d9f19ba2c7-dirty\", GitCommit:\"8ca1d9f19ba2c75dfbca058ecfeb11d4b39d9e9f\", GitTreeState:\"dirty\", BuildDate:\"2017-09-18T18:00:44Z\", GoVersion:\"go1.8.3\", Compiler:\"gc\", Platform:\"linux/amd64\"}\r\nServer Version: version.Info{Major:\"1\", Minor:\"9+\", GitVersion:\"v1.9.0-alpha.0.723+8ca1d9f19ba2c7-dirty\", GitCommit:\"8ca1d9f19ba2c75dfbca058ecfeb11d4b39d9e9f\", GitTreeState:\"dirty\", BuildDate:\"2017-09-18T21:00:48Z\", GoVersion:\"go1.8.3\", Compiler:\"gc\", Platform:\"linux/amd64\"}\r\n```\r\n- Install tools: local-up-cluster.sh\r\n\r\n/cc @rootfs @jsafrane ",
  "closed_at": "2017-09-20T17:01:40Z",
  "closed_by": {
    "avatar_url": "https://avatars0.githubusercontent.com/u/13653959?v=4",
    "events_url": "https://api.github.com/users/k8s-github-robot/events{/privacy}",
    "followers_url": "https://api.github.com/users/k8s-github-robot/followers",
    "following_url": "https://api.github.com/users/k8s-github-robot/following{/other_user}",
    "gists_url": "https://api.github.com/users/k8s-github-robot/gists{/gist_id}",
    "gravatar_id": "",
    "html_url": "https://github.com/k8s-github-robot",
    "id": 13653959,
    "login": "k8s-github-robot",
    "node_id": "MDQ6VXNlcjEzNjUzOTU5",
    "organizations_url": "https://api.github.com/users/k8s-github-robot/orgs",
    "received_events_url": "https://api.github.com/users/k8s-github-robot/received_events",
    "repos_url": "https://api.github.com/users/k8s-github-robot/repos",
    "site_admin": false,
    "starred_url": "https://api.github.com/users/k8s-github-robot/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/k8s-github-robot/subscriptions",
    "type": "User",
    "url": "https://api.github.com/users/k8s-github-robot"
  },
  "comments": 2,
  "comments_url": "https://api.github.com/repos/kubernetes/kubernetes/issues/52674/comments",
  "created_at": "2017-09-18T21:09:13Z",
  "events_url": "https://api.github.com/repos/kubernetes/kubernetes/issues/52674/events",
  "html_url": "https://github.com/kubernetes/kubernetes/issues/52674",
  "id": 258622125,
  "labels": [
    {
      "color": "e11d21",
      "default": false,
      "description": "Categorizes issue or PR as related to a bug.",
      "id": 105146071,
      "name": "kind/bug",
      "node_id": "MDU6TGFiZWwxMDUxNDYwNzE=",
      "url": "https://api.github.com/repos/kubernetes/kubernetes/labels/kind/bug"
    },
    {
      "color": "d2b48c",
      "default": false,
      "description": "Categorizes an issue or PR as relevant to SIG Storage.",
      "id": 169428334,
      "name": "sig/storage",
      "node_id": "MDU6TGFiZWwxNjk0MjgzMzQ=",
      "url": "https://api.github.com/repos/kubernetes/kubernetes/labels/sig/storage"
    }
  ],
  "labels_url": "https://api.github.com/repos/kubernetes/kubernetes/issues/52674/labels{/name}",
  "locked": false,
  "milestone": null,
  "node_id": "MDU6SXNzdWUyNTg2MjIxMjU=",
  "number": 52674,
  "performed_via_github_app": null,
  "repository_url": "https://api.github.com/repos/kubernetes/kubernetes",
  "state": "closed",
  "title": "fc volume can't be attached with \"MountVolume.WaitForAttach failed\"",
  "updated_at": "2017-09-20T17:01:40Z",
  "url": "https://api.github.com/repos/kubernetes/kubernetes/issues/52674",
  "user": {
    "avatar_url": "https://avatars0.githubusercontent.com/u/19844283?v=4",
    "events_url": "https://api.github.com/users/mtanino/events{/privacy}",
    "followers_url": "https://api.github.com/users/mtanino/followers",
    "following_url": "https://api.github.com/users/mtanino/following{/other_user}",
    "gists_url": "https://api.github.com/users/mtanino/gists{/gist_id}",
    "gravatar_id": "",
    "html_url": "https://github.com/mtanino",
    "id": 19844283,
    "login": "mtanino",
    "node_id": "MDQ6VXNlcjE5ODQ0Mjgz",
    "organizations_url": "https://api.github.com/users/mtanino/orgs",
    "received_events_url": "https://api.github.com/users/mtanino/received_events",
    "repos_url": "https://api.github.com/users/mtanino/repos",
    "site_admin": false,
    "starred_url": "https://api.github.com/users/mtanino/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/mtanino/subscriptions",
    "type": "User",
    "url": "https://api.github.com/users/mtanino"
  }
}