{
  "active_lock_reason": null,
  "assignee": null,
  "assignees": [],
  "author_association": "NONE",
  "body": "**What did you do?**\r\n\r\nUpgraded to Grafana 4.0.0\r\n\r\n**What did you expect to see?**\r\n\r\nSnazzy charts as always.\r\n\r\n**What did you see instead? Under which circumstances?**\r\n\r\nPrometheus ran out of filehandles, didn't crash, but stopped ingesting new data.\r\n\r\nGrafana 4.0.0 introduces a bug in which each chart data gather is issued in a new HTTP connection, and these connections appear to be kept alive in Grafana even though they are never used again. The issue is described here: https://github.com/grafana/grafana/issues/6759\r\n\r\nClearly Grafana needs to fix this on their end, but it exposes a problem in that Prometheus can be DoSed simply by opening too many connections. Prometheus should be able to fend off a misbehaving frontend without stopping backend data ingestion.\r\n\r\n**Environment**\r\n\r\n* System information:\r\n\r\n```\r\nLinux 3.13.0-76-generic x86_64\r\n```\r\n\r\n* Prometheus version: \r\n\r\n```\r\nprometheus, version 1.4.1 (branch: master, revision: 2a89e8733f240d3cd57a6520b52c36ac4744ce12)\r\n  build user:       root@e685d23d8809\r\n  build date:       20161128-09:59:22\r\n  go version:       go1.7.3\r\n```\r\n\r\n* Alertmanager version: N/A\r\n\r\n* Prometheus configuration file: N/A\r\n\r\n* Alertmanager configuration file: N/A\r\n\r\n* Logs:\r\n\r\nThousands of lines like this:\r\n```\r\nERRO[2900] http: Accept error: accept tcp [::]:9090: accept4: too many open files; retrying in 1s\r\nERRO[2898] http: Accept error: accept tcp [::]:9090: accept4: too many open files; retrying in 1s\r\nERRO[2898] Error refreshing service xxx_exporter: Get http://localhost:8500/v1/catalog/service/xxx_exporter?index=47790194&wait=30000ms: dial tcp 127.0.0.1:8500: socket: too many open files  source=consul.go:252\r\nERRO[2900] Error dropping persisted chunks: open /prometheus/data/1b/949dcb022d6cfb.db: too many open files  source=storage.go:1495\r\nWARN[2900] Series quarantined.                           fingerprint=7795383ca895e3d7 metric=node_netstat_TcpExt_TCPHPAcks{environment=\"production\", host=\"xxx\", instance=\"xxx\", job=\"node_exporter\", role=\"xxx\", zone=\"xxx\"} reason=open /prometheus/data/77/95383ca895e3d7.db: too many open files source=storage.go:1646\r\nERRO[2900] Error while checkpointing: open /prometheus/data/heads.db.tmp: too many open files  source=storage.go:1252\r\nERRO[2900] Error dropping persisted chunks: open /prometheus/data/1b/94b35810940463.db: too many open files  source=storage.go:1495\r\nERRO[2900] Error while checkpointing: open /prometheus/data/heads.db.tmp: too many open files  source=storage.go:1252\r\nWARN[2900] Series quarantined.                           fingerprint=baf8faede9e50c85 metric=node_vmstat_nr_tlb_local_flush_all{environment=\"production\", host=\"xxx\", instance=\"xxx\", job=\"node_exporter\", role=\"xxx\", zone=\"xxx\"} reason=open /prometheus/data/ba/f8faede9e50c85.db: too many open files source=storage.go:1646\r\n```\r\n",
  "closed_at": "2016-12-06T15:01:45Z",
  "closed_by": {
    "avatar_url": "https://avatars2.githubusercontent.com/u/4948210?v=4",
    "events_url": "https://api.github.com/users/fabxc/events{/privacy}",
    "followers_url": "https://api.github.com/users/fabxc/followers",
    "following_url": "https://api.github.com/users/fabxc/following{/other_user}",
    "gists_url": "https://api.github.com/users/fabxc/gists{/gist_id}",
    "gravatar_id": "",
    "html_url": "https://github.com/fabxc",
    "id": 4948210,
    "login": "fabxc",
    "node_id": "MDQ6VXNlcjQ5NDgyMTA=",
    "organizations_url": "https://api.github.com/users/fabxc/orgs",
    "received_events_url": "https://api.github.com/users/fabxc/received_events",
    "repos_url": "https://api.github.com/users/fabxc/repos",
    "site_admin": false,
    "starred_url": "https://api.github.com/users/fabxc/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/fabxc/subscriptions",
    "type": "User",
    "url": "https://api.github.com/users/fabxc"
  },
  "comments": 19,
  "comments_url": "https://api.github.com/repos/prometheus/prometheus/issues/2238/comments",
  "created_at": "2016-12-01T06:24:49Z",
  "events_url": "https://api.github.com/repos/prometheus/prometheus/issues/2238/events",
  "html_url": "https://github.com/prometheus/prometheus/issues/2238",
  "id": 192764053,
  "labels": [],
  "labels_url": "https://api.github.com/repos/prometheus/prometheus/issues/2238/labels{/name}",
  "locked": true,
  "milestone": null,
  "node_id": "MDU6SXNzdWUxOTI3NjQwNTM=",
  "number": 2238,
  "performed_via_github_app": null,
  "repository_url": "https://api.github.com/repos/prometheus/prometheus",
  "state": "closed",
  "title": "Grafana 4.0.0 causes Prometheus denial of service",
  "updated_at": "2019-03-24T02:20:57Z",
  "url": "https://api.github.com/repos/prometheus/prometheus/issues/2238",
  "user": {
    "avatar_url": "https://avatars3.githubusercontent.com/u/39406?v=4",
    "events_url": "https://api.github.com/users/sodabrew/events{/privacy}",
    "followers_url": "https://api.github.com/users/sodabrew/followers",
    "following_url": "https://api.github.com/users/sodabrew/following{/other_user}",
    "gists_url": "https://api.github.com/users/sodabrew/gists{/gist_id}",
    "gravatar_id": "",
    "html_url": "https://github.com/sodabrew",
    "id": 39406,
    "login": "sodabrew",
    "node_id": "MDQ6VXNlcjM5NDA2",
    "organizations_url": "https://api.github.com/users/sodabrew/orgs",
    "received_events_url": "https://api.github.com/users/sodabrew/received_events",
    "repos_url": "https://api.github.com/users/sodabrew/repos",
    "site_admin": false,
    "starred_url": "https://api.github.com/users/sodabrew/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/sodabrew/subscriptions",
    "type": "User",
    "url": "https://api.github.com/users/sodabrew"
  }
}